### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by JaninaPi** [raspberrypilearning/test-detectives#1]
- In step 2, instructions for how to install IDLE for non-Raspbian users would be great.
- In step 4, the `assert` command isn't introduced in any way, so I added "In Python, you can do this using the built-in command `assert`." at the end of the top paragraph. OK?

**Comment by martinohanlon** [comment]
Re step 2 - I will create an ingredient and add it in
Re step 4 - thats fine thanks

**Comment by JaninaPi** [comment]
- super subtle reminder to add in the python3/idle ingredient :)
- In step 4, I added a bit to the 'What is the point of assertions?' section, please check that it makes sense as it is.

**Comment by martinohanlon** [comment]
Thank you, I have added the python 2 ingredient.

Thats great, thank you.
